version: '2'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  api:
    tty: true
    stdin_open: true
    entrypoint: ["sh", "bin/entrypoint"]
    build:
      context: .
      dockerfile: ./Dockerfile.be
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
    ports:
      - "3000:3000"
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    depends_on:
      - db
    volumes:
      - .:/api
  client:
    stdin_open: true
    build:
      context: ./client/
      dockerfile: ./Dockerfile.fe
    ports:
      - "8080:8080"
    command: yarn --silent start
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules
